presets = ["debian", "claude-code", "rust"]

[vm]
image = "airlock:dev"

[env]
# We can always build natively inside vm
SUPERVISOR_BUILD_HOST = "true"
# We can use host's docker image
SKIP_DEV_IMAGE_BUILD = "true"
# Allow --dangerously-skip-permissions inside vm
IS_SANDBOX = "1"
# Git configs
GIT_AUTHOR_NAME = "${GIT_AUTHOR_NAME:-}"
GIT_AUTHOR_EMAIL = "${GIT_AUTHOR_EMAIL:-}"
GIT_COMMITTER_NAME = "${GIT_COMMITTER_NAME:-}"
GIT_COMMITTER_EMAIL = "${GIT_COMMITTER_EMAIL:-}"
CARGO_TARGET_DIR = "/tmp/cargo"

[disk]
size = "20 GB"

[mounts.claude-json]
missing = "fail"
source = "~/.ez/claude.json"
target = "~/.claude.json"

[network.sockets.docker]
host = "~/.docker/run/docker.sock"
guest = "/var/run/docker.sock"

