#!/bin/bash
#MISE description="Go wild"
#MISE depends=["build:dev", "build:dev-image"]
#MISE raw=true
#MISE quiet=true
#USAGE arg <feature>
set -euo pipefail

feat=$usage_feature
exec target/debug/ez go --session="$feat" --login -- \
  claude --dangerously-skip-permissions --effort=high --name="$usage_feature" --worktree="$usage_feature"
