# Fedora/RHEL/CentOS dnf/yum package manager

[network.rules.fedora-packages]
allow = [
    "mirrors.fedoraproject.org",
    "download.fedoraproject.org",
    "dl.fedoraproject.org",
    "mirror.centos.org",
    "vault.centos.org",
    "cdn-ubi.redhat.com",
    "rhui.REGION.aws.ce.redhat.com",
]
